# Generated by Django 5.0.1 on 2024-01-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
